### PR TITLE
 created buttons to switch between Light and Dark theme

### LINKED ISSUE #3: Dark theme
- Introduce light and dark theme with a custom switcher

### PR DESCRIPTION
**Pull request by Rio-Nyx**
### Description
Dark and light theme for the application

Fixes #3 

### Type of Change:
- Code
- User Interface

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

**Changes**
 - Two independant buttons were created to switch between light theme and dark theme. 
  - Light theme is set as default.
  - Changes to sidebar color to adjust with dark theme

### CODE REVIEW

**Review by tusharnankani — COMMENTED** [review]
image

Could you also change these labels to white, when switched to Dark mode?

You have written a function for that, but there's a mix up of variables, please look into it. This would do the job.

```javascript
// function to change the color of all text labels
function allLabelColor(textColor){
	var labels = document.getElementsByTagName("label");
	for (var i=0, max=labels.length; i < max; i++) {
 		labels[i].style.color = textColor;
	}
}
```

**Comment by Rio-Nyx** [comment]
I fixed that part. Can you kindly review it now?

**Comment by garimasingh128** [comment]
Can you host your current version with the theme switcher on Netlify or somewhere, so I can see how it actually performs in production? Just post the link here in comments. The code looks good, I see a little issue in design, so I will confirm that.

**Comment by Rio-Nyx** [comment]
The link -->  https://tender-boyd-d2bc53.netlify.app/

**Comment by garimasingh128** [comment]
- can you implement a switcher/toggle button instead of the 2 buttons for light and dark?
- Please change the download button in the left pane while you are at it. Anything will do but it should match the aesthetics.

**Comment by Rio-Nyx** [comment]
- Impleneted the toggle switch
- changed the download button and added some styling.
_I hope the color of toggle switch is enough to match with the dark theme._

**Comment by garimasingh128** [comment]
- Add conditional rendering to the 'dark theme' text. When light mode is enabled, keep the text as dark theme and vice versa.
-  [Optional but would be preferred] Change the default color of the marker to white in case of dark theme.

Since there are so many additional functionalities that you performed, I would label the issue as 'hard' and assign scores according to it if you can complete the above tasks.

**Comment by Rio-Nyx** [comment]
Does 'conditional rendering' means -- displaying the label text as "light theme"  in dark mode and "dark theme" in light mode .?

**Comment by garimasingh128** [comment]
yup

**Comment by Rio-Nyx** [comment]
Both the issues are fixed now.

**Comment by garimasingh128** [comment]
Great work!

**Pull request merged**
